### ISSUE TITLE
Error 400 - invalid redirect_uri

### ISSUE THREAD

**Issue by AdeTheux** [SeydX/homebridge-mercedesme#11]
**Describe the bug**
Error 400 after clicking on the START button to initiate authentication

**To Reproduce**
Plugin installed and configured with client ID and secret. Redirect URL configured with http://home.mydomain.tld:PORTCONFIG/callback
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/1615367/101891315-2bc4f180-3ba2-11eb-9f2b-4fc84ec1b5a7.png">

Accessing http://home.mydomain.tld:PORTCONFIG shows me the START button. Clicking on START leads me to a MB error page with "error 400"
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1615367/101891286-223b8980-3ba2-11eb-90e2-a2ce40bc8779.png">

**Expected behavior**
I should be redirected to the MB login page to get my code.

**Screenshots**
See above.

**Additional context**
Latest version of plugin and homebridge, iOS 14.

**Comment by SeydX** [comment]
@AdeTheux 

pls check your callback uri in the mb developer console.

**Comment by AdeTheux** [comment]
It's set to http://home.mydomain.tld:PORTCONFIG/callback, so the same domain:PORT I access to see the START button. That's how I understand the it from the doc. Is that not correct?

**Comment by AdeTheux** [comment]
OK so now I don't have the error 400 anymore, but after clicking on start, it just loads forever. I'm not being redirected to the MB login page 🤔

**Comment by AdeTheux** [comment]
Still tried many variants of this but same error. I've followed each step of the documentation though.

**Comment by woodyard** [comment]
I have this error:
[1/2/2021, 3:17:40 PM] [MercedesPlatform] Mercedes E220d: An error occurred during initialising the API!
[1/2/2021, 3:17:40 PM] [MercedesPlatform] Response Error: 400 Bad Request

I can't access the :3000 page anymore. Saw it once and hit start, but got the same error as mentioned in this post. I enabled remote auth and copied the code to the config.

**Comment by anasiot** [comment]
Hello , i have the same error mentioned when I click on start any idea ?

**Comment by SeydX** [comment]
Should be fixed in v2, coming soon

**Comment by SeydX** [comment]
v2 is online, please check the Readme and example-config
