### ISSUE TITLE
I don't get the battery status displayed in the AppleHome

### ISSUE THREAD

**Issue by Beat540** [SeydX/homebridge-mercedesme#12]
Good day
the plug-in works perfectly, thanks. Doors and windows as well as the light are displayed. Unfortunately, I don't get the battery status displayed in the AppleHome. I added the Electric Vehicle Status BYOCAR API. My CAR (H247) and country are also listed. The same problem is also with Fuel Status BYOCAR and Pay As You Drive Insurance BYOCAR. Thanks for your feedback

**Comment by jamoir** [comment]
I also have this issue. I have an EQC and happy to get involved and test.

**Comment by SeydX** [comment]
Should be fixed in v2, coming soon

**Comment by SeydX** [comment]
v2 is online, please check the Readme and example-config
