### ISSUE TITLE
“An error occurred during initialising the API!”

### ISSUE THREAD

**Issue by lsmith07** [SeydX/homebridge-mercedesme#13]
I’m getting an error message in the Homebridge log after clicking the Start button in the browser:  “An error occurred during initialising the API!”  Followed by “Response Error:  400 Bad Request”

Everything is updated according to instructions.

**Comment by anasiot** [comment]
Same here

**Comment by SeydX** [comment]
Should be fixed in v2, coming soon

**Comment by SeydX** [comment]
v2 is online, please check the Readme and example-config
