### ISSUE TITLE
EQC

### ISSUE THREAD

**Issue by jamoir** [SeydX/homebridge-mercedesme#14]
Hi,

Has anyone managed to get this working with their EQC yet? Be great to be able to view battery %.

Thanks,
Jamie

**Comment by kiddigital** [comment]
@jamoir , within the [Beta version of Domoticz](https://www.domoticz.com/downloads/) there is also an implementation of the MercedesMe API which should be able to read-out the battery.

You can find quite some info on the [MercedesMe Forum Topic](https://www.domoticz.com/forum/viewtopic.php?t=33734) how to get it up-and-running.

Maybe you can give it a try?

(@SeydX , sorry for trying to get people to 'cross-over' to Domoticz, that is not my intention. As the main author of that specific Domoticz module I am interested in the experience of different users and I haven't come across a EQC owner yet to give it a try :) . Just hoping that maybe @jamoir can just try Domoticz and let me know his experiences.)

**Comment by jamoir** [comment]
Hi,

I'm always keen to help, also a developer which might be handy.

The functionality I'm after though is battery status on HomeKit (iPhone etc).  And also the ability to unlock and put windows down from HomeKit.

Happy to help where I can to achieve that, preferably using homebridge as I already have that running on a pi in the house doing other HomeKit bridging.

Cheers,
Jamie

**Comment by kiddigital** [comment]
@jamoir , thx for your response. Your aim is clear and Domoticz can not help you here (at least at the moment).

Would you be able and willing to spend a little time on testing the Domoticz module? It is sufficient to run the latest Beta and only activate the MercedesMe Connect module. You can run it in a VM or just install the (Windows) binary :) thx

**Comment by SeydX** [comment]
Added in v2, coming soon

**Comment by SeydX** [comment]
v2 is online, please check the Readme and example-config
