### ISSUE TITLE
1.3.0

### ISSUE THREAD

**Issue by pjbarnett** [SeydX/homebridge-mercedesme#17]
Just to note I attempted 1.3.0 beta in Homebridge. However I noticed this plug-in was ignoring a 60s Poll and doing it every 5s.

Just thought you might want to know.

**Comment by pjbarnett** [comment]
Just to note this is still happening on the latest 1.3.1 release build

**Comment by SeydX** [comment]
Fixed in v2, coming soon

**Comment by SeydX** [comment]
v2 is online, please check the Readme and example-config
