### ISSUE TITLE
Is there an appetite for some of us to branch off this project?

### ISSUE THREAD

**Issue by jamoir** [SeydX/homebridge-mercedesme#19]
I'm not sure if the developer for this plugin is interested but I would be keen to work on this plugin and make it work a bit like the Tesla one. It sounds really amazing. With it you can lock/unlock, start pre-condition etc. I would also like it to show the battery charge levels.

**Comment by AdeTheux** [comment]
Just fork it if can make it better 🙂 No one has heard back from a while, and a few of us seem to face the same issue about the initial setup not working, unfortunately.

**Comment by SeydX** [comment]
V2 is online
