### ISSUE TITLE
Polling API Error

### ISSUE THREAD

**Issue by jamoir** [SeydX/homebridge-mercedesme#21]
Hi,

I've installed v2 and run the setup. Got the new setup working and it got back a token. But in the status I get this error:

[3/2/2021, 08:10:47] [MercedesPlatform] It seems that it is not possible anymore to grant access with your stored token!

Thanks,
Jamie

**Comment by jamoir** [comment]
Just to add some more info. If I authorise and restart there is no error. When I go back into settings and tick 'electric vehicle' thats when I get the above error.

**Comment by SeydX** [comment]
@jamoir 

v2.0.1 is online. 

**NOTE:** If you have an electric vehicle and had issues with "Electric Vehicle" enabled in the config, please refresh your access token via Config UI X after the update and restart homebridge

1. Update plugin
2. Restart homebridge
3. Refresh Token
4. Restart Homebridge

![hb_mercedesme_ui_refreshToken](https://user-images.githubusercontent.com/34152761/109654574-9dd62280-7b62-11eb-9350-be1a81e052f6.gif)

**Comment by jamoir** [comment]
Hi,

That worked like a charm. Thanks for a speedy reply.

Only bit I can’t see is the battery status in Home on the iPhone.

Thanks,
Jamie

On 2 Mar 2021, at 13:22, Seyd <notifications@github.com> wrote:

﻿

@jamoir<https://github.com/jamoir>

v2.0.1 is online.

NOTE: If you have an electric vehicle and had issues with "Electric Vehicle" enabled in the config, please refresh your access token via Config UI X after the update and restart homebridge

  1.  Update plugin
  2.  Restart homebridge
  3.  Refresh Token
  4.  Restart Homebridge

[hb_mercedesme_ui_refreshToken]<https://user-images.githubusercontent.com/34152761/109654574-9dd62280-7b62-11eb-9350-be1a81e052f6.gif>

**Comment by SeydX** [comment]
@jamoir 

battery is within the accessories


https://user-images.githubusercontent.com/34152761/109676294-dbde4100-7b78-11eb-9262-23f6f1a6b067.MP4

**Comment by jamoir** [comment]
That’s brilliant got it. Think I could find it as I had the tiles grouped.

Is there anyway to have the battery status as it’s own tile so it can be seen quickly in the home dash? Even if it has to be a humidity tile.

On 2 Mar 2021, at 16:01, Seyd <notifications@github.com> wrote:

﻿

@jamoir<https://github.com/jamoir>

battery is within the accessories

https://user-images.githubusercontent.com/34152761/109676294-dbde4100-7b78-11eb-9262-23f6f1a6b067.MP4

**Comment by SeydX** [comment]
@jamoir 

v2.0.3 is online

added new option in config „humiditySensor“ to show battery also as a separate humidity sensor

**Comment by jamoir** [comment]
Amazing… thank you so much!

On 2 Mar 2021, at 23:57, Seyd <notifications@github.com<mailto:notifications@github.com>> wrote:



@jamoir<https://github.com/jamoir>

v2.0.3 is online

added new option in config „humiditySensor“ to show battery also as a separate humidity sensor

**Comment by jamoir** [comment]
Hi,

Is there any chance in changing the humidity to a light. Problem with humidity is you can’t have the tile in your favourites on displayed normally. So you always have to drill down. I think as a light it makes more sense.

Hopefully Apple will add some more functionality to HomeKit this year.

This plugin is working really well though.

Thanks again.

Cheers,
Jamie

On 3 Mar 2021, at 10:52, Jamie Reynolds ***@***.***> wrote:

﻿ Amazing… thank you so much!

On 2 Mar 2021, at 23:57, Seyd ***@***.******@***.***>> wrote:



@jamoir<https://github.com/jamoir>

v2.0.3 is online

added new option in config „humiditySensor“ to show battery also as a separate humidity sensor
