### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by pjbarnett** [SeydX/homebridge-mercedesme#22]
Please could you clarify the redirect URL and if its changed from V1?
I'm getting:-

400 - Invalid redirect_uri

This is when I click the start authentication after filling in client id etc. Previously on v1 it was http://localhost:4010/callback

Thanks

**Comment by SeydX** [comment]
You need to change your redirect uri, see here

https://github.com/SeydX/homebridge-mercedesme#important

**Comment by pjbarnett** [comment]
Sorry I did try that 1st but I am clearly missing something. To log into my homebridge the address is http://192.168.10.145:8581. So is that the port number I use in the mercedes me redirect or the 8080? I tried the 8080 but i noticed the link is still 8581 in the address bar when I get the 400 message.

Sorry if I am just having a moment!

Thanks.

**Comment by SeydX** [comment]
Port 8080 in the description is only a example. You need your config ui x port. In his case, its 8581

**Comment by pjbarnett** [comment]
Thank you. I realised I was doing it off my Homebridge running linux computer and I spotted this before when playing with the Magic Mirror. By doing the settings from another computer logged into the homebridge UI page, it worked 1st time.

Thank you again for your help.
