### ISSUE TITLE
Fuel Level/Battery Charge is not displayed in Home app

### ISSUE THREAD

**Issue by NGDM** [SeydX/homebridge-mercedesme#23]
**Describe the bug**
The Fuel Level/Battery Charge accessory is shown in my HomeBridge Accessories overview together with other Doors/Windows/Locks accessories.
In the Home app I can find them all except for the Fuel Level/Battery Charge one.

**To Reproduce**
Plugin v1 or v2, happens in both.
Followed regular setup for a A180d.
Authentication successful, logs are fine, accessories are shown and up-to-date.
Only in the Home app the fuel level accessory is missing.

**Expected behavior**
Accessory or Sensor in the Apple Home app which shows the current fuel level or battery charge.

**Comment by SeydX** [comment]
The battery service is within the other accessories, see here


https://user-images.githubusercontent.com/34152761/109646369-65314b80-7b58-11eb-95cf-9100eea94d1a.MP4

**Comment by NGDM** [comment]
Alright, didn't know that!
Thanks.
Not quite how I would've liked it (as a seperate sensor) but I assume this is a limitation of the Home platform?

**Comment by SeydX** [comment]
@NGDM 

You re right. Home App doesn’t allow to show battery as a separate accessory

**Comment by SeydX** [comment]
@NGDM 

added new option in config „humiditySensor“ to show battery also as a separate humidity sensor
