### ISSUE TITLE
Authentification failure

### ISSUE THREAD

**Issue by JochenOc** [SeydX/homebridge-mercedesme#24]
after typing in the client id, client secret, fin and pressing the next button:

RedirectURL:Port/?error_description=The requested scope is invalid, unknown, malformed, or exceeds that which the client is permitted to request.&error=invalid_scope

appears and homebridge main window appears.

the DebugLog output is as follows:
[2.3.2021, 20:48:56] [Homebridge UI] [homebridge-mercedesme] Incoming Request: /authCode
[2.3.2021, 20:49:06] [Homebridge UI] [homebridge-mercedesme] Terminating child process...
[2.3.2021, 20:49:06] [Homebridge UI] [homebridge-mercedesme] Child process ended

**Comment by SeydX** [comment]
@JochenOc 

can u write something about your car pls? Model? Year? Electric?

**Comment by LeBaron90** [comment]
have the same issue. In Version 1 everything worked. GLC 300 MildHybrid, 2020 model

**Comment by SeydX** [comment]
@JochenOc @LeBaron90 

can u do following steps and send me a screenshot from it

1. Login at https://id.mercedes-benz.com/ciam/auth/login
2. Open https://access-history.mercedes-benz.com/
3. Click on „Application“

![7DCE6861-BF36-4970-818B-87F5A1676F8F](https://user-images.githubusercontent.com/34152761/109711629-5ae67000-7b9f-11eb-8b23-1679a2a0db8a.jpeg)


Your created application should be listed there

Expand it and send a screenshot from it pls

Something like this

![4E767A27-9DD2-40AE-A1CF-B59514446681](https://user-images.githubusercontent.com/34152761/109711375-178c0180-7b9f-11eb-9c62-3a7fbfbe278b.png)

**Comment by JochenOc** [comment]
![grafik](https://user-images.githubusercontent.com/79938477/109711947-b6b0f900-7b9f-11eb-9de2-42114fb8b3d2.png)

**Comment by JochenOc** [comment]
I've an E-Class E300de, model 2020 MildHybrid

**Comment by LeBaron90** [comment]
![Uploading Bildschirmfoto 6.jpg…]()

**Comment by SeydX** [comment]
@JochenOc @LeBaron90 

it seems v2 doesnt have access to the electric vehicle endpoint

you need to add the electric vehicle endpoint to your app like the other endpoints before

electric vehicle endpoint: https://developer.mercedes-benz.com/products/electric_vehicle_status/

after adding the endpoint to your app, pls try to authenticate it with homebridge again

**Comment by JochenOc** [comment]
I've found the problem.. your plug in seems to identify that my car was electric car, so i added the battery level API and now it works.

**Comment by LeBaron90** [comment]
worked, thank you very much! Grüsse aus der CH (greets from CH) (:
![Bildschirmfoto 8](https://user-images.githubusercontent.com/15858705/109713180-2ffd1b80-7ba1-11eb-9fc7-f94110e91b83.jpg)

**Comment by SeydX** [comment]
Super freut mich, dann kann das hier ja geschlossen werden :)

**Comment by phis5533** [comment]
@LeBaron90 

Hello,
it seems you have a GLC 300e hybrid in your screenshot ? 
What kind of API did you configure to the Mercedes dev portal.
I've tried to enroll every API but it fails everytime 👎 
with the url : 
`http://192.168.0.49:8581/?error_description=The%20requested%20scope%20is%20invalid,%20unknown,%20malformed,%20or%20exceeds%20that%20which%20the%20client%20is%20permitted%20to%20request.&error=invalid_scope#`

Can you help me please ?
Thx
Philippe
