### ISSUE TITLE
Setting up plugin in Hoobs

### ISSUE THREAD

**Issue by pellehebs** [SeydX/homebridge-mercedesme#26]
Hey SeydX

I am completely psyched about this plugin and im desperately trying to install it in Hoobs. Is that even possible? And what about the "token" section? Please please please help.

**Comment by SeydX** [comment]
@pellehebs 

HOOBS is bot supported by this plugin

**Comment by pellehebs** [comment]
Damn it. Thanks though! :) 




Pelle Emil Hebsgaard / www.pellehebsgaard.dk 
pellehebs@gmail.com / +45 30 24 67 16

Manager 
Sten Hassing Møller 
sten@teamplayers.dk 
www.teamplayers.dk

**Comment by SeydX** [comment]
If you use HOOBs and want to use the plugin, there is an easy way to do it

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge
