### ISSUE TITLE
400 - Invalid redirect_uri

### ISSUE THREAD

**Issue by malikramires** [SeydX/homebridge-mercedesme#27]
Hallo SeyedX,

leider bekomme ich immer wieder den Fehler 400 - Invalid redirect_uri angezeigt sobald ich "Start Authentification" ausführe

Wenn ich auf https://id.mercedes-benz.com/ciam/auth/login#/ gehe kommt folgende Fehlermeldung

![Bildschirmfoto 2021-03-04 um 18 30 45](https://user-images.githubusercontent.com/35766823/110004464-c18e9980-7d17-11eb-80e4-8456b92cc84a.png)

In der Acces History sind keine Einträge zu sehen, wenn ich dann auf Application klicke wird mir nur Amazon Alexa angezeigt aber nicht homebridge.
Client ID & Secret und VIN sind korrekt

Als Redirect URL gebe ich die IP von meinem Raspi an auf dem Homebridge läuft mit dem Port 80

(Die Freigabe dafür erfolgt hier über ein Wormhole von dataplicity, sowohl der eigens generierte Link dafür um als auch die direkte IP Adresse bringen leider keine Änderung

**Comment by SeydX** [comment]
@malikramires 

dein Config UI  X läuft auf Port 80 ??

**Comment by malikramires** [comment]
@SeydX Laut anzeige im Terminal über SSH läuft dieser auf 8581 aber auch da klappt es leider nicht wenn ich das als Redirect URL eingebe,den Port 80 habe ich heute zusätzlich ausprobiert weil ich bei 8581 nicht weiterkomme

**Comment by SeydX** [comment]
Kannst du mir ein Screenshot von der App den du auf Mercedes Developer Seite erstellt hast schicken bitte

**Comment by malikramires** [comment]
![Bildschirmfoto 2021-03-04 um 18 38 36](https://user-images.githubusercontent.com/35766823/110005523-de779c80-7d18-11eb-9f90-5d1213db684e.png)

**Comment by SeydX** [comment]
Was für ein Auto? Model? Jahr?

**Comment by malikramires** [comment]
C250 S205 2018

**Comment by SeydX** [comment]
@malikramires 

Alle endpoints hinzugefügt zur App?? Auch "Electric Vehicle Status" bitte hinzufügen (https://developer.mercedes-benz.com/products/electric_vehicle_status/)

**Comment by malikramires** [comment]
@SeydX  Alle Endpoints sind drin,Electric hatte zwar gefehlt aber auch das hinzufügen schmeisst mir leider nach wie vor 400 - Invalid redirect_uri  raus

**Comment by malikramires** [comment]
@SeydX  Ich hab jetzt das Plugin samt Config entfernt und neu Installiert,zuerst die letzte Version vor 2.0

Alles neu konfiguriert und dann auf die aktuellste Version geupdatet.

Dann die Homebridge über die IP mit dem Zusatz des Port in der Adresszeile aufgerufen die Authentification neu versucht und jetzt hat alles geklappt.Vermutlich irgendwo ein problem in der Config gehabt
