### ISSUE TITLE
Invalid redirect 400

### ISSUE THREAD

**Issue by anasiot** [SeydX/homebridge-mercedesme#28]
Hi 

i m’ not able to get the authentification pop up it’s saying invalid redirect  400
I have checked the dev app mercedes and the ui x port and it’s matching so don’t understand what is the problem
![BBEA99E4-9D1C-40E5-8F58-CB15B8FC3956](https://user-images.githubusercontent.com/76408878/110102577-3e1b8980-7da5-11eb-969b-0da4f5b3a118.png)
![E7E34F40-5138-488E-ACC1-B1E4A1CD1964](https://user-images.githubusercontent.com/76408878/110102582-3fe54d00-7da5-11eb-8f87-cf44fd2d84a7.jpeg)
![6FEADC0C-D5AE-4005-A985-C2E2DF17B0B0](https://user-images.githubusercontent.com/76408878/110102586-407de380-7da5-11eb-9afd-4d18de1f9616.jpeg)

**Comment by SeydX** [comment]
@anasiot 

can u try with following redirect url on the mercedes developer site

``http://192.168.1.33:8581`` _(this one is without "/" at the end)_

**Comment by anasiot** [comment]
When I try this it open a new window of the UIx and at the url i have :
![A8569FCA-070A-4E97-B3EB-7EE9AA4E7479](https://user-images.githubusercontent.com/76408878/110114533-1af8d600-7db5-11eb-8c1f-ef401755c47e.jpeg)

**Comment by SeydX** [comment]
@anasiot 

can u post your config.json pls & which car? model? year?

**Comment by anasiot** [comment]
There is nothing that I have modified after installation on json

  "cars": [],
            "platform": "MercedesPlatform",
            "name": "MercedesPlatform",
            "debug": false
        }
    ]

the model w204 , model 2013
}

**Comment by SeydX** [comment]
@anasiot 

your car is not supported

See here:

https://developer.mercedes-benz.com/products/fuel_status/details

https://developer.mercedes-benz.com/products/vehicle_status/details

https://developer.mercedes-benz.com/products/vehicle_lock_status/details

https://developer.mercedes-benz.com/products/electric_vehicle_status/details

**Comment by marcelo0561** [comment]
Hi @SeydX.
I'm having the same problem. As you can see the Redirect URL in the Mercedes API platform is the URL of the Config UI X 
![image](https://user-images.githubusercontent.com/80131103/110178372-418f2f00-7dfe-11eb-88ec-d38faa0548e9.png)

But when I try to refresh the plugin to get the authorization token it just redirects me to the homepage of the Homebridge with the following URL:
http://192.168.2.24:8581/?error_description=The%20requested%20scope%20is%20invalid,%20unknown,%20malformed,%20or%20exceeds%20that%20which%20the%20client%20is%20permitted%20to%20request.&error=invalid_scope#.

My car is model W177 year 2020.

Thank you!

**Comment by SeydX** [comment]
@marcelo0561 

added all endpoints to app??

look here https://github.com/SeydX/homebridge-mercedesme#first-steps-obtain-client-id-and-client-secret

pls also add Electric Vehicle Status Endpoint to app

**Comment by marcelo0561** [comment]
@SeydX 
Oh amazing that works now!
Thank you for the super quick message and for the continued work on this! Looking forward to more features in the future. 😁
