### ISSUE TITLE
Requested Scope invalid

### ISSUE THREAD

**Issue by pjbarnett** [SeydX/homebridge-mercedesme#29]
Since updating to latest v1.3.3 and homebridge-config-ui-x v4.40.0, I noticed the authentication expired and errored. So I deleted and tried manually and receive the following when I click the authentication.

http://xx.xx.xx.xx:xxxx/?error_description=The%20requested%20scope%20is%20invalid,%20unknown,%20malformed,%20or%20exceeds%20that%20which%20the%20client%20is%20permitted%20to%20request.&error=invalid_scope#.

Any ideas?

**Comment by SeydX** [comment]
@pjbarnett 

added also the electric vehicle endpoint to your app on mercedes benz developer site?

**Comment by pjbarnett** [comment]
guilty as charged! (pardon the pun). I have now and all working. Thank you.
