### ISSUE TITLE
Running Homebridge in Docker with Portainer

### ISSUE THREAD

**Issue by ChrisKoh83** [SeydX/homebridge-mercedesme#3]
Hey, great project! 

I'm trying to set it up on my Homebridge instance that is running in a docker container. 

I set up port 3000 for my first car but I'm unable to connect the website 
http://192.168.200.2:3000

Do I have to publish the port 3000 from the host to the container?

**Comment by ChrisKoh83** [comment]
ok, I finally got it! Where was nothing to do with port exposing... just rtfm ;)

but now I'm facing another issue:

`[8/23/2020, 9:54:55 PM] [MercedesPlatform] Mercedes API currently not available.
[8/23/2020, 9:55:06 PM] [MercedesPlatform] Mercedes B200: Can not change lock state. Not supported at the moment!
[8/23/2020, 9:55:06 PM] [MercedesPlatform] Mercedes B200: Vehicle/Car trunk lock secured
[8/23/2020, 9:55:07 PM] [MercedesPlatform] Mercedes B200: Vehicle/Car trunk lock secured`

**Comment by SeydX** [comment]
Thats not an issue from the plugin. The Mercedes API is currently down

**Comment by ChrisKoh83** [comment]
> Thats not an issue from the plugin. The Mercedes API is currently down

ok :) 

but the Website says:

![Bildschirmfoto 2020-08-23 um 22 00 21](https://user-images.githubusercontent.com/13451391/90987564-2b213480-e58c-11ea-9d13-0009fb65a5b2.png)

**Comment by SeydX** [comment]
Yes but the Mercedes Server and Router have some timeout problems atm to handle the client request in a given time. It takes too long and you got a Gateway Timeout error > API not available

I have the same prob atm and other user too

**Comment by glk3504matic** [comment]
Is this still an issue? I am getting the same thing happening.

**Comment by glk3504matic** [comment]
Not getting an API error anymore, but the state does not change even with the car locked and unlocked

**Comment by SeydX** [comment]
@all

Mercedes has some issues atm.

![A02C2611-12CA-4991-B0E6-DD562EBCACA9](https://user-images.githubusercontent.com/34152761/91472928-75f6c100-e898-11ea-9456-10a8a26f51ca.jpeg)
