### ISSUE TITLE
Hybrid

### ISSUE THREAD

**Issue by pjbarnett** [SeydX/homebridge-mercedesme#30]
Any chance it can show fuel and electric level? Unless I’m probably missing something.

**Comment by SeydX** [comment]
@pjbarnett 

currently it is not possible to show both. Battery Service from Apple Home can only show one value, you must decide it in config

**Comment by pjbarnett** [comment]
Understood. Thanks

**Comment by SeydX** [comment]
@pjbarnett 

added in v2.1.1

https://github.com/SeydX/homebridge-mercedesme/blob/bc0848373b7f77ac21cf135375b6c0cf18c0ab06/example-config.json#L42

**Comment by pjbarnett** [comment]
AMAZING! well done and thank you.
