### ISSUE TITLE
There is no access token configured for this car. This car will be skipped.

### ISSUE THREAD

**Issue by e1l52** [SeydX/homebridge-mercedesme#32]
Thanks for this great plugin.

I ran through all needed steps, but still get this error message :
_There is no access token configured for this car. This car will be skipped._

Any idea what's missing or what I did wrong ?

**Comment by SeydX** [comment]
@e1l52 

To use this plugin you need homebridge-config-ui-x. If installed, take a look at this. The Plugin needs an access token, and config ui x will generate one by setting up the plugin as you can see below:

![hb_mercedesme_ui](https://user-images.githubusercontent.com/34152761/111423646-e65c1700-86f0-11eb-8575-d8995e582b03.gif)

**Comment by e1l52** [comment]
Hi SeydX, I moved my installation from Hoobs to Homebridge. Now I am able to run the configuration in Config-ui-x.
When I create a project and add the local ip e.g. http://192.168.1.30 of my Config-UI-X it always results in this https://localhost address.
Any idea why this is happening ?

<img width="1110" alt="Screenshot 2021-03-23 at 17 26 31" src="https://user-images.githubusercontent.com/60822096/112182134-4f65f200-8bfd-11eb-9f02-e3e948794619.png">

**Comment by SeydX** [comment]
Change the redirect url to http://192.168.1.30/

**Comment by e1l52** [comment]
Thanks a lot !
I found the way how to change. What an awful Mercedes developer page, unbelievable how you could manage that.
I have now the right Redirect URL. But - I still get this error.
<img width="912" alt="Screenshot 2021-03-23 at 23 42 22" src="https://user-images.githubusercontent.com/60822096/112229103-a20dd100-8c32-11eb-9b0e-d219c7573ab6.png">

**Comment by mmondrup** [comment]
When I click the "Start Authentication", the plug-in simply just loops me back to my general Config-ui-x in a separate window.
Shows to some extend that my redirect URL is working but the Mercedes plug-in does not seem to intercept the request and proceed to the token generation.
Any help will be appreciated.
BR
Michael
