### ISSUE TITLE
Can't authorise, what's wrong?

### ISSUE THREAD

**Issue by powertomac** [SeydX/homebridge-mercedesme#35]
<img width="781" alt="Screenshot 2021-04-13 at 18 45 28" src="https://user-images.githubusercontent.com/56325690/114589908-6c379780-9c88-11eb-805f-a45420ed4d10.png">

**Comment by powertomac** [comment]
or in other words...how can I be sure that the redirect url is correct?
I found my ip address of the raspberry pi, but where can I find the port number? Is It the number in Config UI X if you go to "UI-Settings"?

**Comment by glk3504matic** [comment]
Same issue here.

**Comment by powertomac** [comment]
Found the issue, you don't have to add the port number, now it's working. So go to the Config UI and just copy the IPv4 address on the left side and paste it like:
http://xxx.xxx.x.xxx
That's it

**Comment by glk3504matic** [comment]
I tried that and still running into the issue
