### ISSUE TITLE
Cant Open Portfrom Config

### ISSUE THREAD

**Issue by malikramires** [SeydX/homebridge-mercedesme#5]
Hello SeydX,

unfortanetly i can not open the Port from Config in my Browser, I am on another Device.

Homebridge runs on Raspberry Pi 2B

Homebridge Interface on iMac 

I typed in IP and then :Portfrom Config (the numbers of course) but i cant reach it.

We can also talk in German if possible

Thanks

**Comment by SeydX** [comment]
pls try v1.1.2
