### ISSUE TITLE
New OAuth endpoints

### ISSUE THREAD

**Issue by 13az13** [SeydX/homebridge-mercedesme#6]
**Describe the bug**
The current authentication process, localhost:PORT fails after pressing start and Mercedes return a message:
“Reason: invalid_client
Description: The given client credentials were not valid”

I believe this is because they have updated their OAuth provider and the endpoints in the package need to be updated. Their announcement page is here https://developer.mercedes-benz.com/oauth_migration

**To Reproduce**
Setup as per the instructions
Navigate to the localhost auth page
Receive your custom webpage to start the process
Click start
Mercedes returns the error above

**Expected behavior**
Token details to be returned and passed into the plugin config

Many thanks in advance and please let me know if I can help or test in any way, appreciate all your efforts with this plugin and look forward to using it

**Comment by franzel61** [comment]
Deae Seydx,

First of all thanks for developing this extension. I installed it in the synology docker ( which rund nearly perfect for more than a year) following you rules with a click on remote access. I got the invalid msg and tried to find remote key without success. What kind of information you need for the analysis?

All the best Franzel

**Comment by mikesamo** [comment]
Hello, I got the same issue here, 

![image](https://user-images.githubusercontent.com/547838/96347694-682c1380-1071-11eb-8e7c-0dd8b3d25c16.png)

**Comment by SeydX** [comment]
Fix coming soon

**Comment by mikesamo** [comment]
if you need someone to test it I am here :)

**Comment by 13az13** [comment]
> if you need someone to test it I am here :)

Likewise, appreciate your efforts on this plugin and happy to help where I can with testing etc. Look forward to the fix

Cheers

**Comment by SeydX** [comment]
New oAuth endpoints added in v1.1.2 (https://github.com/SeydX/homebridge-mercedesme/commit/7c385cbb7ccc87127dc6ce34d42e9927b0538deb)

If errors occur please delete the app created on the Mercedes Me developer page and grant access for:

- Fuel Status
- Pay As You Drive Insurance
- Vehicle Lock Status
- Vehicle Status

**Comment by mikesamo** [comment]
Hello thanks for the update still not working... and deleted my apps in Mercedes created from scrattch

**Comment by 13az13** [comment]
Thanks @SeydX - working a treat. Appreciate your time in updating this
