### ISSUE TITLE
Updated still issue with Auth

### ISSUE THREAD

**Issue by mujtabakhokhar** [SeydX/homebridge-mercedesme#8]
**Describe the bug**
Oops
Looks like something is not right. Please contact your administrator.
400 - Invalid redirect_uri

**To Reproduce**
Setup as per the instructions
Navigate to the localhost auth page
Receive your custom webpage to start the process
Click start
Mercedes returns the error above

**Expected behavior**
Token details to be returned and passed into the plugin config

**Comment by SeydX** [comment]
It seems the your redirect uri is not right in your mercedes developer console

Can u post s screenshot from your mercedes dev console pls

**Comment by mujtabakhokhar** [comment]
my bad, 
fixed it. i had entered the IP rather than leaving it as localhost 

Thanks
