### ISSUE TITLE
Remote Authentication is failing with 400 - Invalid redirect_uri

### ISSUE THREAD

**Issue by kravena** [SeydX/homebridge-mercedesme#9]
My setup is configured to run Homebridge from a Linux VM as per the homebridge documentation.

Due to this, I am opening the portal via a Windows 10 PC (ip : 192.168.1.100) which connects to the Homebridge VM at 192.168.1.58. I'm running the plugin port at 3050.

Due to this, i need to use Remote authentication, as the Localhost will point to x.x.x.100 instead of x.x.x.58 for the Homebridge VM.

I can connect to the Mercedes remote authentication page at http://x.x.x.58:3050 which gives me the HOMEBRIDGEMERCEDESME page with the start button, but the error message "400 - Invalid redirect_uri" is displayed with I press start.

The URL being displayed is 

https://id.mercedes-benz.com/as/authorization.oauth2?response_type=code&client_id=<REMOVED>&redirect_uri=http%3A%2F%2Flocalhost%3A3050%2Fcallback&scope=mb%3Avehicle%3Ambdata%3Avehiclestatus%20mb%3Avehicle%3Ambdata%3Afuelstatus%20mb%3Avehicle%3Ambdata%3Avehiclelock%20mb%3Avehicle%3Ambdata%3Apayasyoudrive%20offline_access

It seems the URL being returned is referencing LOCALHOST instead of the IP address of the home bridge VM 192.168.1.58.

I have tried with various uri's in the mercedes developer console

http://localhost      (default)
http://192.168.1.58:3050
http://192.168.1.58:3050/callback
http://homebridge-vm:3050
http://homebridge-vm:3050/callback

I have also ensured the following are applied to the mercedes add

Fuel Status BYOCAR
Pay As You Drive Insurance BYOCAR
Vehicle Lock Status BYOCAR
Vehicle Status BYOCAR

I have also deleted and recreated the mercedes developer app.

I did manage to get a code from "?code=" when manipulating firefox and entered this into the plugin and I got a different error in the log. I got this by removing everything in the failed url from the uri message from the &redirect_uri onwards.

[11/2/2020, 4:20:01 PM] [MercedesPlatform] C250D: An error occurred during initialising the API!
[11/2/2020, 4:20:01 PM] [MercedesPlatform] Response Error: 400 Bad Request

**Comment by kravena** [comment]
Got it working, don't use Edge Chrome.

When I did the whole thing from Firefox, including being signed into the Mercedes Dev website, all worked.

**Comment by SeydX** [comment]
ah good to know, thx

**Comment by andre4nap** [comment]
I've have same problem. I try to authenticate my homebridge app from my laptop through url http://homebridge.local:3000
When I press "Start" button, I receive the error  "400 - Invalid redirect_uri" and the url is `https://id.mercedes-benz.com/as/authorization.oauth2?response_type=code&client_id=xxx&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&scope=mb%3Avehicle%3Ambdata%3Avehiclestatus%20mb%3Avehicle%3Ambdata%3Afuelstatus%20mb%3Avehicle%3Ambdata%3Avehiclelock%20mb%3Avehicle%3Ambdata%3Apayasyoudrive%20offline_access`
If I replace localhost with homebridge.local, in debug console, appear this error 
```[MercedesPlatform] Mercedes: An error occurred during initialising the API!
[MercedesPlatform] Response Error: 400 Bad Request``` 

So I've installed GUI on my RasPi and I've tried with chromium. Successfully generate token, but when restart Homebridge there is this error
```
[01/12/2020, 14:34:01] [MercedesPlatform] Mercedes: Initializing API with stored token..
[01/12/2020, 14:34:02] [MercedesPlatform] Mercedes: API successfull initialized
2020-12-01T13:34:02.197Z MercedesApi Mercedes: GET [PENDING] https://api.mercedes-benz.com/vehicledata/v2/vehicles/<VIN>/containers/vehiclelockstatus
2020-12-01T13:34:02.741Z MercedesApi Mercedes: GET [ERROR]
[01/12/2020, 14:34:02] [MercedesPlatform] It seems that it is not possible anymore to grant access with your stored token! Please remove the storage folder under /var/lib/homebridge, restart the plugin and authorize the plugin again!
2020-12-01T13:34:02.745Z MercedesPlatform Mercedes: Lock Status could not be polled successfully! Trying again in 10s
2020-12-01T13:34:02.747Z MercedesPlatform Mercedes: {"errorLock":true,"errorVehicle":false,"errorFuel":false,"lock":true,"vehicle":false,"fuel":false,"rePoll":10000}```

**Comment by glennmurley15** [comment]
You need the trailing slash in the redirect URI for it to work!

`http%3A%2F%2F192.168.2.200%3A8581%2F`

`http://192.168.2.200:8581/`

**Comment by glennmurley15** [comment]
Or even easier, remember to NOT add a trailing slash when adding the redirect URI

`http://192.168.2.200:8581`
